var china = {
    login: "登陆",
    alldevice: "所有设备",
    condevice: "控制设备",
    security: "安防设备",
    detectdevice: "监控设备",
    adddevice: "+添加设备",
    apartment: "户型名称:",
    apartmentlist: "户型列表",
    nowalarm: "实时报警数据",
    describe: "描述",
    time: "时间",
    location: "地点",
    devices: "设备",
    manipulate: "操作",
    process: "处理",
    temperature: "温度",
    humidity: "湿度",
    PM25: "PM2.5",
    next: "下一步",
    cancel: "取消",
    true: "确定",
    name: "名称",
    selectdevice: "已选择设备",
    room: "房间",
    status: "状态",
    details: "详情",
    disable: "禁用",
    able: "启用",
    return: "返回",
    failure: "失败!",
    success: "成功!",
    offline: "离线",
    online: "在线",
    data: "数据",
    down: "下行",
    types: "类型",
    delete: "删除",
    update: "修改",
    open: "开",
    close: "关",
    temp: "温度",
    humi: "湿度",
    update: "更新",
    unlimited: "无限制",
    number: "序号",
    floor: "楼层",
    all: "全部",
    createtime: "创建时间",
    add: "添加",
    // ------------// adddevice
    addfail1: "设备名称不符合规则",
    addfail2: "请先选择要添加的设备!",
    addfail3: "房间错误,请重新选择!!",
    addfail4: "详情过长!!",
    addfail5: "设备类型错误,请重新选择!!",
    // ------------// addroom
    addroom: "添加房间",
    // ------------// addroomnum
    addroomnum: "添加户型",
    addroomnumber: "户型门牌",
    // ----------
    linkdevices: "关联设备详情",
    Disassociate: "解除关联",
    clink: "点击关联设备",
    // -----------down//
    switch: "开关",
    updatetime: "更新设备时间",
    alarm: "临时解除警报",
    temphuim: "设置温湿度最大最小值",
    uptime: "设置上传间隔",
    samtime: "设置采样频率",
    heardtime: "设置心跳间隔",
    devicestop: "设备停止",
    //-------------alarm list
    alarmlist: "报警列表",
    processed: "已处理",
    unprocessed: "未处理",
    allprocessed: "全部处理",
    // ------------ user
    userdetails: "用户资料",
    oldpassword: "旧密码",
    newpassword: "新密码",
    mobile: "手机号",
    permission: "权限",
    super: "超级管理员",
    admin: "管理员",
    man: "普通用户",
    adduser: "添加用户",
}

var english = {
    login: "login in",
    alldevice: "All Devices",
    condevice: "controlling device",
    security: "Security Devices",
    detectdevice: "Monitoring Devices",
    adddevice: "+Add Device",
    apartment: "Apartment",
    apartmentlist: "Apartment List",
    nowalarm: "Real-time alarm data",
    describe: "describe",
    time: "time",
    location: "location",
    devices: "devices",
    manipulate: "manipulate",
    process: "process",
    temperature: "temperature",
    humidity: "humidity",
    PM25: "PM2.5",
    next: "next",
    cancel: "cancel",
    true: "true",
    name: "name",
    selectdevice: "device",
    room: "room",
    status: "status",
    details: "details",
    disable: "disable",
    able: "able",
    return: "return",
    failure: "failure!",
    success: "success!",
    offline: "offline",
    online: "online",
    data: "data",
    down: "down",
    types: "types",
    delete: "delete",
    update: "update",
    open: "open",
    close: "close",
    temp: "temp",
    humi: "humi",
    update: "update",
    unlimited: "unlimited",
    number: "number",
    floor: "floor",
    all: "all",
    createtime: "create time",
    add: "Add",
    // ------------// adddevice
    addfail1: "Device name does not match the rule!",
    addfail2: "Please select the device you want to add first!",
    addfail3: "Room error, please re-select!",
    addfail4: "The details are too long!!",
    addfail5: "The device type is wrong, please re-select!",
    // ------------// addroom
    addroom: "add room",
    // ------------// addroomnum
    addroomnum: "add Apartment",
    addroomnumber: "Number",
    // ----------
    linkdevices: "Associate device",
    Disassociate: "Disassociate",
    clink: "Click to link",
    // -----------down//
    switch: "switch",
    updatetime: "Update device time",
    alarm: "Temporarily lift the alarm",
    temphuim: "maximum temperature and humidity",
    uptime: "Set upload interval",
    samtime: "sampling frequency",
    heardtime: "heartbeat interval",
    devicestop: "Device stop",
    //-------------alarm list
    alarmlist: "alarm list",
    processed: "processed",
    unprocessed: "unprocessed",
    allprocessed: "all",
    // ------------ user
    userdetails: "user details",
    oldpassword: "old password",
    newpassword: "password",
    mobile: "mobile",
    permission: "permission",
    super: "super",
    admin: "admin",
    man: "general",
    adduser: "add user",

}

export function init(se) {
    if (se == 1) {
        return english
    } else {
        return china
    }
}

export default {
    init,
}